package ORM;
// Generated 9 ene. 2020 14:07:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comunidad generated by hbm2java
 */
public class Comunidad  implements java.io.Serializable {


     private int idCom;
     private String nomCom;
     private Set provincias = new HashSet(0);

    public Comunidad() {
    }

	
    public Comunidad(int idCom, String nomCom) {
        this.idCom = idCom;
        this.nomCom = nomCom;
    }
    public Comunidad(int idCom, String nomCom, Set provincias) {
       this.idCom = idCom;
       this.nomCom = nomCom;
       this.provincias = provincias;
    }
   
    public int getIdCom() {
        return this.idCom;
    }
    
    public void setIdCom(int idCom) {
        this.idCom = idCom;
    }
    public String getNomCom() {
        return this.nomCom;
    }
    
    public void setNomCom(String nomCom) {
        this.nomCom = nomCom;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


