package ORM;
// Generated 9 ene. 2020 14:07:44 by Hibernate Tools 4.3.1



/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int idLoc;
     private Provincia provincia;
     private String nomLocalidad;

    public Localidad() {
    }

    public Localidad(int idLoc, Provincia provincia, String nomLocalidad) {
       this.idLoc = idLoc;
       this.provincia = provincia;
       this.nomLocalidad = nomLocalidad;
    }
   
    public int getIdLoc() {
        return this.idLoc;
    }
    
    public void setIdLoc(int idLoc) {
        this.idLoc = idLoc;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNomLocalidad() {
        return this.nomLocalidad;
    }
    
    public void setNomLocalidad(String nomLocalidad) {
        this.nomLocalidad = nomLocalidad;
    }




}


