package ORM;
// Generated 9 ene. 2020 14:07:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int idProv;
     private Comunidad comunidad;
     private String nomProv;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int idProv, Comunidad comunidad, String nomProv) {
        this.idProv = idProv;
        this.comunidad = comunidad;
        this.nomProv = nomProv;
    }
    public Provincia(int idProv, Comunidad comunidad, String nomProv, Set localidads) {
       this.idProv = idProv;
       this.comunidad = comunidad;
       this.nomProv = nomProv;
       this.localidads = localidads;
    }
   
    public int getIdProv() {
        return this.idProv;
    }
    
    public void setIdProv(int idProv) {
        this.idProv = idProv;
    }
    public Comunidad getComunidad() {
        return this.comunidad;
    }
    
    public void setComunidad(Comunidad comunidad) {
        this.comunidad = comunidad;
    }
    public String getNomProv() {
        return this.nomProv;
    }
    
    public void setNomProv(String nomProv) {
        this.nomProv = nomProv;
    }
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


