package ORM;
// Generated 6 feb. 2020 13:29:03 by Hibernate Tools 4.3.1

import java.io.Serializable;




/**
 * EmpPlantilla generated by hbm2java
 */
public class EmpPlantilla implements Serializable{


    private int numEmp;

    public EmpPlantilla() {
    }

    public Integer getNumEmp() {
        return this.numEmp;
    }
    public void setNumEmp(int numEmp) {
        this.numEmp = numEmp;
    }
    
    
    




}


